"""Can_090 from the Gallery map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="gallery_can_090",
    label="🥫",
    title="Blue studio can",
    mesh="../objects/gallery_can_090.obj",
    collision="cylinder",
    size=(0.033, 0.0575),
    rgba=(0.1725, 0.4157, 0.7765, 1.0),
    rest_z=0.0575,
    drop_z=0.0675,
    initial_pose=(2.6, 0.0, 0.0),
    viewer={"glb": "/models/gallery/gallery_can_090.glb", "preNormalized": True},
)
