"""Can_180 from the Gallery map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="gallery_can_180",
    label="🥫",
    title="Can 180",
    mesh="../objects/gallery_can_180.stl",
    collision="cylinder",
    size=(0.033, 0.0575),
    rgba=(0.1725, 0.4157, 0.7765, 1.0),
    rest_z=0.0575,
    drop_z=0.0675,
)
