"""Mug_h50 from the Gallery map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="gallery_mug_h50",
    label="☕",
    title="Mug h50",
    mesh="../objects/gallery_mug_h50.stl",
    collision="cylinder",
    size=(0.0425, 0.0475),
    rgba=(0.7882, 0.2275, 0.1882, 1.0),
    rest_z=0.0475,
    drop_z=0.5575,
)
