"""Mug_h50 from the Gallery map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="gallery_mug_h50",
    label="☕",
    title="Red display mug",
    mesh="../objects/gallery_mug_h50.obj",
    collision="cylinder",
    size=(0.0425, 0.0475),
    rgba=(0.7882, 0.2275, 0.1882, 1.0),
    rest_z=0.0475,
    drop_z=0.5575,
    initial_pose=(3.0, 3.2, 0.0),
    viewer={"glb": "/models/gallery/gallery_mug_h50.glb", "preNormalized": True},
)
