"""Carton_New from the Pantry map (generated by sim/tools/roblox_to_innate.py).

SHORTENED so the robot can actually reach it. The delivery bench it sits on is
240 mm high and the carton was 149 mm tall, putting its centre at 315 mm -- past
the ~300 mm the arm works below, with no vertical freedom in the base to make
up the difference. Both challenges that use it (pantry_restock,
pantry_stocktake) were therefore unwinnable, and nothing caught it: the reach
check measured horizontal distance only.

Only the HEIGHT changes. The grasp axis is already 50 mm and the footprint is
what keeps it stable on the bench, so shrinking those would repeat the mistake
that put blaze_documents on the floor. 80 mm tall clears BOTH surfaces: the 240 mm bench (centre 280 mm) and the
255 mm shelf bay it is delivered to (centre 295 mm). The bay is the tighter of
the two and is what sets the number.
"""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="pantry_carton_new",
    label="?",
    title="Carton New",
    mesh="../objects/pantry_carton_new.stl",
    mesh_scale=0.8065,
    collision="box",
    size=(0.0464, 0.0250, 0.0400),
    rgba=(0.698, 0.3059, 0.1882, 1.0),
    rest_z=0.0400,
    drop_z=0.3425,
)
