"""Carton_Oats from the Pantry map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="pantry_carton_oats",
    label="?",
    title="Carton Oats",
    mesh="../objects/pantry_carton_oats.stl",
    collision="box",
    size=(0.0575, 0.031, 0.0400),
    rgba=(0.1882, 0.3608, 0.6588, 1.0),
    rest_z=0.0400,
    drop_z=0.2325,
)
