"""Carton_Rice from the Pantry map (generated by sim/tools/roblox_to_innate.py)."""

# Visuals: sim/tools/build_pantry_props.py; metres at the collision body origin.
from mars_sim_driver.props import Prop

PROP = Prop(
    name="pantry_carton_rice",
    label="C",
    title="Carton Rice",
    mesh="../objects/pantry_carton_rice.obj",
    viewer={"glb": "/models/groceries/pantry_carton_rice.glb", "preNormalized": True},
    collision="box",
    size=(0.0575, 0.031, 0.0400),
    rgba=(0.9333, 0.9059, 0.8471, 1.0),
    initial_pose=(0.4, 1.54, 0),
    rest_z=0.0400,
    drop_z=0.2325,
)
