"""Carton_Rice from the Pantry map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="pantry_carton_rice",
    label="?",
    title="Carton Rice",
    mesh="../objects/pantry_carton_rice.stl",
    collision="box",
    size=(0.0575, 0.031, 0.0400),
    rgba=(0.9333, 0.9059, 0.8471, 1.0),
    rest_z=0.0400,
    drop_z=0.2325,
)
