"""Carton_Tea from the Pantry map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="pantry_carton_tea",
    label="?",
    title="Carton Tea",
    mesh="../objects/pantry_carton_tea.stl",
    collision="box",
    size=(0.0575, 0.031, 0.0400),
    rgba=(0.1804, 0.3608, 0.2588, 1.0),
    rest_z=0.0400,
    drop_z=0.3625,
)
