"""Carton_Tea from the Pantry map (generated by sim/tools/roblox_to_innate.py)."""

# Visuals: sim/tools/build_pantry_props.py; metres at the collision body origin.
from mars_sim_driver.props import Prop

PROP = Prop(
    name="pantry_carton_tea",
    label="C",
    title="Carton Tea",
    mesh="../objects/pantry_carton_tea.obj",
    viewer={"glb": "/models/groceries/pantry_carton_tea.glb", "preNormalized": True},
    collision="box",
    size=(0.0575, 0.031, 0.0400),
    rgba=(0.1804, 0.3608, 0.2588, 1.0),
    initial_pose=(2.24, 0.4, -90),
    rest_z=0.0400,
    drop_z=0.3625,
)
