"""Jar_Curd from the Pantry map (generated by sim/tools/roblox_to_innate.py)."""

# Visuals: sim/tools/build_pantry_props.py; metres at the collision body origin.
from mars_sim_driver.props import Prop

PROP = Prop(
    name="pantry_jar_curd",
    label="J",
    title="Jar Curd",
    mesh="../objects/pantry_jar_curd.obj",
    viewer={"glb": "/models/groceries/pantry_jar_curd.glb", "preNormalized": True},
    collision="cylinder",
    size=(0.043, 0.054),
    rgba=(0.7451, 0.5961, 0.3059, 1.0),
    initial_pose=(-2.24, -0.85, 0),
    rest_z=0.054,
    drop_z=0.324,
)
