"""Jar_Curd from the Pantry map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="pantry_jar_curd",
    label="?",
    title="Jar Curd",
    mesh="../objects/pantry_jar_curd.stl",
    collision="cylinder",
    size=(0.043, 0.054),
    rgba=(0.7451, 0.5961, 0.3059, 1.0),
    rest_z=0.054,
    drop_z=0.324,
)
