"""Jar_Honey from the Pantry map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="pantry_jar_honey",
    label="?",
    title="Jar Honey",
    mesh="../objects/pantry_jar_honey.stl",
    collision="cylinder",
    size=(0.043, 0.054),
    rgba=(0.8078, 0.5804, 0.2118, 1.0),
    rest_z=0.054,
    drop_z=0.194,
)
