"""Jar_Honey from the Pantry map (generated by sim/tools/roblox_to_innate.py)."""

# Visuals: sim/tools/build_pantry_props.py; metres at the collision body origin.
from mars_sim_driver.props import Prop

PROP = Prop(
    name="pantry_jar_honey",
    label="J",
    title="Jar Honey",
    mesh="../objects/pantry_jar_honey.obj",
    viewer={"glb": "/models/groceries/pantry_jar_honey.glb", "preNormalized": True},
    collision="cylinder",
    size=(0.043, 0.054),
    rgba=(0.8078, 0.5804, 0.2118, 1.0),
    initial_pose=(-2.24, 0.8, 0),
    rest_z=0.054,
    drop_z=0.194,
)
