"""Jar_Jam from the Pantry map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="pantry_jar_jam",
    label="?",
    title="Jar Jam",
    mesh="../objects/pantry_jar_jam.stl",
    collision="cylinder",
    size=(0.043, 0.054),
    rgba=(0.698, 0.3059, 0.1882, 1.0),
    rest_z=0.054,
    drop_z=0.194,
)
