"""Jar_New from the Pantry map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="pantry_jar_new",
    label="?",
    title="Jar New",
    mesh="../objects/pantry_jar_new.stl",
    collision="cylinder",
    size=(0.043, 0.054),
    rgba=(0.1882, 0.3608, 0.6588, 1.0),
    rest_z=0.054,
    drop_z=0.304,
)
