"""Jar_New from the Pantry map (generated by sim/tools/roblox_to_innate.py)."""

# Visuals: sim/tools/build_pantry_props.py; metres at the collision body origin.
from mars_sim_driver.props import Prop

PROP = Prop(
    name="pantry_jar_new",
    label="J",
    title="Jar New",
    mesh="../objects/pantry_jar_new.obj",
    viewer={"glb": "/models/groceries/pantry_jar_new.glb", "preNormalized": True},
    collision="cylinder",
    size=(0.043, 0.054),
    rgba=(0.1882, 0.3608, 0.6588, 1.0),
    rest_z=0.054,
    drop_z=0.304,
)
