"""Jar_Pick from the Pantry map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="pantry_jar_pick",
    label="?",
    title="Jar Pick",
    mesh="../objects/pantry_jar_pick.stl",
    collision="cylinder",
    size=(0.043, 0.054),
    rgba=(0.1804, 0.3608, 0.2588, 1.0),
    rest_z=0.054,
    drop_z=0.324,
)
