"""Jar_Stray from the Pantry map (generated by sim/tools/roblox_to_innate.py)."""

# Visuals: sim/tools/build_pantry_props.py; metres at the collision body origin.
from mars_sim_driver.props import Prop

PROP = Prop(
    name="pantry_jar_stray",
    label="J",
    title="Jar Stray",
    mesh="../objects/pantry_jar_stray.obj",
    viewer={"glb": "/models/groceries/pantry_jar_stray.glb", "preNormalized": True},
    collision="cylinder",
    size=(0.0250, 0.0314),
    rgba=(0.698, 0.3059, 0.1882, 1.0),
    initial_pose=(-2.24, -0.55, 0),
    rest_z=0.0314,
    drop_z=0.194,
)
