"""Jar_Stray from the Pantry map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="pantry_jar_stray",
    label="?",
    title="Jar Stray",
    mesh="../objects/pantry_jar_stray.stl",
    mesh_scale=0.5814,
    collision="cylinder",
    size=(0.0250, 0.0314),
    rgba=(0.698, 0.3059, 0.1882, 1.0),
    rest_z=0.0314,
    drop_z=0.194,
)
