"""Tin_Large from the Pantry map (generated by sim/tools/roblox_to_innate.py)."""

# Visuals: sim/tools/build_pantry_props.py; metres at the collision body origin.
from mars_sim_driver.props import Prop

PROP = Prop(
    name="pantry_tin_large",
    label="T",
    title="Tin Large",
    mesh="../objects/pantry_tin_large.obj",
    viewer={"glb": "/models/groceries/pantry_tin_large.glb", "preNormalized": True},
    collision="cylinder",
    size=(0.0725, 0.028),
    rgba=(0.9647, 0.9529, 0.9255, 1.0),
    rest_z=0.028,
    drop_z=0.168,
)
