"""Tin_Small from the Pantry map (generated by sim/tools/roblox_to_innate.py)."""

# Visuals: sim/tools/build_pantry_props.py; metres at the collision body origin.
from mars_sim_driver.props import Prop

PROP = Prop(
    name="pantry_tin_small",
    label="T",
    title="Tin Small",
    mesh="../objects/pantry_tin_small.obj",
    viewer={"glb": "/models/groceries/pantry_tin_small.glb", "preNormalized": True},
    collision="cylinder",
    size=(0.0725, 0.028),
    rgba=(0.7686, 0.8392, 0.8392, 1.0),
    rest_z=0.028,
    drop_z=0.168,
)
