# AUTO-GENERATED by the skill catalog from the physical skills on this robot.
# Regenerated on every skill change — do not edit; edits are overwritten.
"""Typed references to this robot's physical skills.

Import a ref from its recording folder; this package is the generated
definition site the folder shims re-export from:

    from innate_skills.pick_socks import PickSocks  # the usual spelling
    from physical_skills import PickSocks           # same class

Use them anywhere a skill id goes: in an Agent's get_skills() list, or as a
declaration on a Skill (``pick: PickSocks``).
"""

from innate import TrainedSkill


class Music(TrainedSkill):
    """replay skill · 0 episodes"""

    skill_id = 'local/music'

class Replacecactus(TrainedSkill):
    """learned skill · 1 episodes · still in training"""

    skill_id = 'local/replacecactus'

class Test(TrainedSkill):
    """replay skill · 0 episodes"""

    skill_id = 'local/test'

class Wave(TrainedSkill):
    """replay skill · 0 episodes"""

    skill_id = 'local/wave'

class WaveInnateOs(TrainedSkill):
    """Greet someone with a friendly arm wave. Use it when a person arrives or greets the robot, or when asked to say hello or wave. The arm replays a fixed recorded motion and returns to rest, so keep the space in front of the robot clear and do not use it while the gripper is holding something.

    replay skill · 0 episodes
    """

    skill_id = 'innate-os/wave'


def __getattr__(name):
    raise AttributeError(
        f"No physical skill named {name!r} on this robot (deleted, renamed, or not created yet?). "
        'Available: Music, Replacecactus, Test, Wave, WaveInnateOs'
    )
