version: "3.8"
services:
  ros2_container:
    build: .
    container_name: ros2_container
    network_mode: host
    environment:
      # Force CycloneDDS
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      # Tells CycloneDDS to use our container config file
      - CYCLONEDDS_URI=file:///root/cyclonedds_container.xml

      # Optional: domain ID must match host
      - ROS_DOMAIN_ID=0
    volumes:
      - .:/workdir
    tty: true
    stdin_open: true
    # The default is "bridge" network on macOS Docker
