FROM ros:humble

# Install ROS 2 demo nodes
RUN apt-get update && apt-get install -y \
    ros-humble-demo-nodes-cpp \
    iputils-ping \
    netcat \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 11811/udp
# Also the 7400 ports
EXPOSE 7400-7410/udp

COPY fastdds_log_config.xml /etc/fastdds_log_config.xml

ENV RMW_IMPLEMENTATION=rmw_fastrtps_cpp
ENV RMW_FASTRTPS_LOG_CONFIG_FILE=/etc/fastdds_log_config.xml

CMD ["/bin/bash"]
