"""Documents from the Blaze map (generated by sim/tools/roblox_to_innate.py).

NARROWED ON ONE AXIS ONLY, deliberately. A uniform 0.8065x rescale to fit the
gripper shrank the footprint from 115x62 mm to 93x50 mm, and the box then no
longer bridged the shelf support it rests on in blaze_l3: it sat still for
0.8 s, had drifted 46 mm by 4 s, and was on the floor 403 mm away by 12 s. The
other two props on that map never move at all.

Only the grasp axis needs to change -- the gripper closes across the SHORT
horizontal side, so 31 mm -> 25 mm half-extent is the whole requirement.
Length and height are back to their authored values, and that is what keeps it
on the shelf. The visual mesh is now ~12 mm wider than the collider across that
one axis, which is a better trade than a prop that is on the floor before the
robot arrives.
"""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="blaze_documents",
    label="?",
    title="Documents",
    mesh="../objects/blaze_documents.stl",
    collision="box",
    size=(0.0575, 0.0250, 0.0925),
    # Blue, not (0.9333, 0.9059, 0.8471) -- which is BYTE-IDENTICAL to the
    # blaze wall colour: a wall-coloured box on a shelf is invisible by
    # construction, and the probe agent that searched for it never saw box OR
    # shelf. Distinct from the red medicine and green towels. Post-dates the
    # Aug 16 live run.
    rgba=(0.20, 0.35, 0.70, 1.0),
    rest_z=0.0925,
    drop_z=0.2325,
)
