"""Medicine from the Blaze map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="blaze_medicine",
    label="?",
    title="Medicine",
    mesh="../objects/blaze_medicine.stl",
    mesh_scale=0.5814,
    collision="cylinder",
    size=(0.0250, 0.0314),
    # Red, not terracotta-on-orange: the bottle stood against the kitchen's
    # ORANGE splashback in almost its own hue -- a probe agent scanned the
    # kitchen 360 degrees from inside and reported it empty. Red is distinct
    # from the green towels decoy and pops against orange, cream and white.
    # Post-dates the Aug 16 live run.
    rgba=(0.85, 0.10, 0.10, 1.0),
    rest_z=0.0314,
    drop_z=0.304,
)
