"""Photo from the Blaze map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="blaze_photo",
    label="🖼",
    title="Framed photo",
    mesh="../objects/blaze_photo.obj",
    viewer={"glb": "/models/blaze/blaze_photo.glb", "preNormalized": True},
    collision="box",
    size=(0.095, 0.006, 0.115),
    rgba=(0.4392, 0.3059, 0.1725, 1.0),
    initial_pose=(2.35, -1.75, 0),
    rest_z=0.11947,
    drop_z=0.365,
)
