"""Towels from the Blaze map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="blaze_towels",
    label="?",
    title="Towels",
    mesh="../objects/blaze_towels.stl",
    collision="box",
    size=(0.0575, 0.031, 0.0925),
    rgba=(0.1804, 0.3608, 0.2588, 1.0),
    rest_z=0.0925,
    drop_z=0.2325,
)
