#!/usr/bin/env python3

import math
import threading
import time
from typing import Optional

from src.agent.types import (
    NavigationPathMsg,
    NavigationCancelMsg,
    NavigationStatusMsg,
    NavigationFeedbackMsg,
    NavigationWaypoint,
    PositionCmd,
)


class NavigationController:
    """
    Navigation controller that follows paths generated by Nav2.
    Uses topic-based communication instead of action servers.
    """

    def __init__(self, shared_queues):
        self.shared_queues = shared_queues

        # Navigation state
        self.current_path: Optional[NavigationPathMsg] = None
        self.current_status = "IDLE"
        self.is_navigating = False
        self.cancel_requested = False

        # Path following parameters
        self.waypoint_tolerance = 0.3  # meters - tolerance for intermediate waypoints
        self.final_goal_tolerance = 0.1  # meters - tighter tolerance for final goal
        self.orientation_tolerance = 0.1  # radians - for final goal orientation
        self.command_rate = 20.0  # Hz - rate of position commands
        self.feedback_rate = 10.0  # Hz

        # Path following state
        self.current_waypoint_index = 0
        self.final_goal: Optional[NavigationWaypoint] = None

        # Navigation thread
        self.nav_thread: Optional[threading.Thread] = None
        self.nav_thread_stop = threading.Event()

        # Status and feedback publishing
        self.last_status_publish = 0.0
        self.last_feedback_publish = 0.0
        self.status_publish_rate = 5.0  # Hz

    def set_navigation_path(self, path: NavigationPathMsg):
        """Set a new navigation path from Nav2 and start following it."""
        if not path.waypoints:
            print("[NavController] Received empty path")
            self.current_status = "FAILED"
            self._publish_status()
            return

        print(
            f"[NavController] Received navigation path with {len(path.waypoints)} waypoints"
        )

        # Log start and end positions
        start_wp = path.waypoints[0]
        end_wp = path.waypoints[-1]
        print(
            f"[NavController] Path: ({start_wp.x:.2f}, {start_wp.y:.2f}) -> ({end_wp.x:.2f}, {end_wp.y:.2f})"
        )

        # Cancel any existing navigation
        self.cancel_navigation()

        # Set new path
        self.current_path = path
        self.final_goal = path.waypoints[-1]  # Last waypoint is the final goal
        self.cancel_requested = False
        self.current_status = "ACTIVE"
        self.is_navigating = True
        self.current_waypoint_index = 0

        print(
            f"[NavController] Starting path following with {len(path.waypoints)} waypoints"
        )

        # Start navigation thread
        self.nav_thread_stop.clear()
        self.nav_thread = threading.Thread(target=self._navigation_loop, daemon=True)
        self.nav_thread.start()

        # Publish initial status
        self._publish_status()

    def cancel_navigation(self):
        """Cancel current navigation."""
        if self.is_navigating:
            print("[NavController] Canceling navigation")
            self.cancel_requested = True
            self.nav_thread_stop.set()

            if self.nav_thread and self.nav_thread.is_alive():
                self.nav_thread.join(timeout=1.0)

            self.is_navigating = False
            self.current_status = "CANCELED"
            self._publish_status()

            # Clear the path
            self.current_path = None
            self.final_goal = None
            self.current_waypoint_index = 0

    def _get_current_target_waypoint(self):
        """Get the current target waypoint based on progress through the path."""
        if not self.current_path or not self.current_path.waypoints:
            return None

        if self.current_waypoint_index >= len(self.current_path.waypoints):
            return None

        return self.current_path.waypoints[self.current_waypoint_index]

    def _is_waypoint_reached(
        self,
        robot_x: float,
        robot_y: float,
        robot_yaw: float,
        waypoint: NavigationWaypoint,
        is_final: bool = False,
    ) -> bool:
        """Check if robot has reached the given waypoint."""
        # Check position
        dx = waypoint.x - robot_x
        dy = waypoint.y - robot_y
        distance = math.sqrt(dx * dx + dy * dy)

        position_tolerance = (
            self.final_goal_tolerance if is_final else self.waypoint_tolerance
        )
        position_reached = distance < position_tolerance

        # For final waypoint, also check orientation
        if is_final:
            # Calculate angle error (normalize to [-pi, pi])
            angle_error = waypoint.yaw - robot_yaw
            while angle_error > math.pi:
                angle_error -= 2 * math.pi
            while angle_error < -math.pi:
                angle_error += 2 * math.pi

            orientation_reached = abs(angle_error) < self.orientation_tolerance

            # Debug info for final waypoint
            if position_reached and not orientation_reached:
                print(
                    f"[NavController] Position reached but orientation off by {math.degrees(abs(angle_error)):.1f}° (target: {math.degrees(waypoint.yaw):.1f}°, current: {math.degrees(robot_yaw):.1f}°)"
                )

            return position_reached and orientation_reached
        else:
            # For intermediate waypoints, only check position
            return position_reached

    def _navigation_loop(self):
        """Main navigation loop that follows waypoints sequentially."""
        if not self.current_path or not self.current_path.waypoints:
            return

        print(
            f"[NavController] Starting path following with {len(self.current_path.waypoints)} waypoints"
        )

        while not self.nav_thread_stop.is_set() and not self.cancel_requested:
            # Get current robot position and orientation
            robot_pos, robot_quat, _ = self.shared_queues.get_robot_pose()
            robot_x, robot_y = robot_pos[0], robot_pos[1]

            # Convert quaternion to yaw angle
            # robot_quat is [ox, oy, oz, ow] format
            qx, qy, qz, qw = robot_quat[0], robot_quat[1], robot_quat[2], robot_quat[3]
            robot_yaw = math.atan2(
                2.0 * (qw * qz + qx * qy), 1.0 - 2.0 * (qy * qy + qz * qz)
            )

            # Get current target waypoint
            target_waypoint = self._get_current_target_waypoint()

            if target_waypoint is None:
                # No more waypoints - path completed successfully
                print("[NavController] All waypoints reached - path completed!")
                self.current_status = "SUCCEEDED"
                self.is_navigating = False
                self._publish_status()
                break

            # Check if we've reached the current waypoint
            is_final_waypoint = (
                self.current_waypoint_index == len(self.current_path.waypoints) - 1
            )

            if self._is_waypoint_reached(
                robot_x, robot_y, robot_yaw, target_waypoint, is_final_waypoint
            ):
                if is_final_waypoint:
                    # Reached the final goal
                    print(
                        f"[NavController] Reached final goal at ({target_waypoint.x:.2f}, {target_waypoint.y:.2f})"
                    )
                    self.current_status = "SUCCEEDED"
                    self.is_navigating = False
                    self._publish_status()
                    break
                else:
                    # Reached intermediate waypoint, move to next one
                    self.current_waypoint_index += 1
                    next_waypoint = self._get_current_target_waypoint()
                    if next_waypoint:
                        print(
                            f"[NavController] Reached waypoint {self.current_waypoint_index}, moving to ({next_waypoint.x:.2f}, {next_waypoint.y:.2f})"
                        )
                    continue

            # Send position command to move toward current waypoint
            self._send_position_command(
                target_waypoint.x, target_waypoint.y, target_waypoint.yaw
            )

            # Calculate distance to final goal for feedback
            if self.final_goal:
                dx = self.final_goal.x - robot_x
                dy = self.final_goal.y - robot_y
                distance_to_goal = math.sqrt(dx * dx + dy * dy)
                self._publish_feedback(distance_to_goal)

            # Sleep to maintain command rate
            time.sleep(1.0 / self.command_rate)

        # Navigation ended
        if self.cancel_requested:
            self.current_status = "CANCELED"
        elif self.current_status != "SUCCEEDED":
            self.current_status = "FAILED"

        self.is_navigating = False
        self._publish_status()
        print(f"[NavController] Navigation ended with status: {self.current_status}")

    def _send_position_command(
        self, target_x: float, target_y: float, target_yaw: float
    ):
        """Send position command with orientation to simulator."""
        pos_cmd = PositionCmd(
            target_x=target_x, target_y=target_y, target_z=0.0, target_yaw=target_yaw
        )
        try:
            self.shared_queues.agent_to_sim.put_nowait(pos_cmd)
        except:
            pass  # Queue full, skip this command

    def _publish_status(self):
        """Publish navigation status."""
        status_msg = NavigationStatusMsg(status=self.current_status)
        try:
            # Add to sim_to_agent queue for bridge to pick up
            self.shared_queues.sim_to_agent.put_nowait(status_msg)
        except:
            pass

    def _publish_feedback(self, distance_to_goal: float):
        """Publish navigation feedback."""
        now = time.time()
        if now - self.last_feedback_publish >= (1.0 / self.feedback_rate):
            feedback_msg = NavigationFeedbackMsg(distance_to_goal=distance_to_goal)
            try:
                # Add to sim_to_agent queue for bridge to pick up
                self.shared_queues.sim_to_agent.put_nowait(feedback_msg)
            except:
                pass
            self.last_feedback_publish = now

    def get_current_status(self) -> str:
        """Get current navigation status."""
        return self.current_status

    def is_active(self) -> bool:
        """Check if navigation is currently active."""
        return self.is_navigating
