# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Innate Inc
"""Non-blocking Nav2 goals for person following."""

from __future__ import annotations

import math
import threading
import time
from collections.abc import Callable
from dataclasses import dataclass
from typing import TYPE_CHECKING, Protocol, cast

from action_msgs.msg import GoalStatus
from geometry_msgs.msg import PoseStamped
from nav2_msgs.action import NavigateToPose
from rclpy.action import ActionClient

from brain_client.common.enums import StrEnum
from brain_client.perception.person_follow import FollowTarget
from brain_client.perception.pose import Pose, resolve_local_goal

if TYPE_CHECKING:
    from rclpy.impl.rcutils_logger import RcutilsLogger
    from rclpy.node import Node
    from rclpy.task import Future

_MIN_REFRESH_SECONDS = 1.0
_MIN_GOAL_SHIFT_M = 0.08
_MIN_GOAL_YAW_RAD = math.radians(7.0)
_PERSON_FOLLOW_SELECTOR = "person_follow"


class _GoalHandle(Protocol):
    accepted: bool

    def get_result_async(self) -> Future: ...

    def cancel_goal_async(self) -> Future: ...


class FollowGoalState(StrEnum):
    IDLE = "idle"
    SENDING = "sending"
    ACTIVE = "active"
    CANCELING = "canceling"
    UNAVAILABLE = "unavailable"
    FAILED = "failed"


@dataclass(frozen=True)
class FollowGoalSnapshot:
    state: FollowGoalState
    reason: str
    goal: Pose | None
    pending: int
    active: int


class GazeNavigator:
    """Own the short-lived Nav2 goals generated by person following."""

    def __init__(
        self,
        node: Node,
        logger: RcutilsLogger,
        get_odom_pose: Callable[[], Pose | None],
        get_navigation_mode: Callable[[], str | None],
    ) -> None:
        self._node = node
        self._logger = logger
        self._get_odom_pose = get_odom_pose
        self._get_navigation_mode = get_navigation_mode
        self._client = ActionClient(node, NavigateToPose, "/navigate_to_pose")
        self._lock = threading.Lock()
        self._state = FollowGoalState.IDLE
        self._reason = ""
        self._epoch = 0
        self._pending = 0
        self._canceling = 0
        self._handles: list[_GoalHandle] = []
        self._last_goal: Pose | None = None
        self._last_sent_at = 0.0
        self._closed = False
        self._client_destroyed = False

    @property
    def state(self) -> FollowGoalState:
        with self._lock:
            return self._state

    @property
    def reason(self) -> str:
        with self._lock:
            return self._reason

    @property
    def failed(self) -> bool:
        return self.state in {FollowGoalState.UNAVAILABLE, FollowGoalState.FAILED}

    def snapshot(self) -> FollowGoalSnapshot:
        with self._lock:
            return FollowGoalSnapshot(
                state=self._state,
                reason=self._reason,
                goal=self._last_goal,
                pending=self._pending,
                active=len(self._handles),
            )

    def update_target(self, target: FollowTarget) -> None:
        with self._lock:
            if self._closed:
                return
        if self.failed:
            return
        if not target.needs_goal:
            self.cancel("holding distance")
            return
        if self._get_navigation_mode() == "mapping":
            self._fail(FollowGoalState.UNAVAILABLE, "navigation unavailable while mapping")
            return
        base_pose = self._get_odom_pose()
        if base_pose is None:
            self._fail(FollowGoalState.UNAVAILABLE, "odometry unavailable")
            return
        if not self._client.server_is_ready():
            self._fail(FollowGoalState.UNAVAILABLE, "navigate_to_pose unavailable")
            return

        local_goal = (
            target.forward_m * math.cos(target.bearing_rad),
            target.forward_m * math.sin(target.bearing_rad),
            target.bearing_rad,
        )
        goal = resolve_local_goal(base_pose, local_goal)
        now = time.monotonic()
        with self._lock:
            if now - self._last_sent_at < _MIN_REFRESH_SECONDS or not self._goal_changed(goal):
                return
            epoch = self._epoch
            self._pending += 1
            self._state = FollowGoalState.SENDING
            self._reason = ""
            self._last_goal = goal
            self._last_sent_at = now

        goal_msg = NavigateToPose.Goal()
        goal_msg.pose = self._pose_stamped(goal)
        goal_msg.behavior_tree = _PERSON_FOLLOW_SELECTOR
        self._client.send_goal_async(goal_msg).add_done_callback(lambda future: self._on_goal(future, epoch))

    def cancel(self, reason: str = "") -> None:
        with self._lock:
            already_idle = not self._handles and self._pending == 0
            self._epoch += 1
            handles = self._handles
            self._handles = []
            self._last_goal = None
            self._last_sent_at = 0.0
            self._reason = reason
            self._state = FollowGoalState.IDLE if already_idle else FollowGoalState.CANCELING
        self._cancel_handles(handles)
        self._settle()

    def close(self) -> None:
        with self._lock:
            if self._closed:
                return
            self._closed = True
        self.cancel("closed")
        self._settle()

    def _goal_changed(self, goal: Pose) -> bool:
        previous = self._last_goal
        if previous is None:
            return True
        shift = math.hypot(goal[0] - previous[0], goal[1] - previous[1])
        yaw = abs(math.atan2(math.sin(goal[2] - previous[2]), math.cos(goal[2] - previous[2])))
        return shift >= _MIN_GOAL_SHIFT_M or yaw >= _MIN_GOAL_YAW_RAD

    def _pose_stamped(self, goal: Pose) -> PoseStamped:
        goal_x, goal_y, goal_yaw = goal
        pose = PoseStamped()
        pose.header.frame_id = "odom"
        pose.header.stamp = self._node.get_clock().now().to_msg()
        pose.pose.position.x = goal_x
        pose.pose.position.y = goal_y
        pose.pose.orientation.z = math.sin(goal_yaw / 2.0)
        pose.pose.orientation.w = math.cos(goal_yaw / 2.0)
        return pose

    def _on_goal(self, future: Future, epoch: int) -> None:
        try:
            handle = cast(_GoalHandle | None, future.result())
        except Exception as error:  # noqa: BLE001 — action transport failures must terminate motion
            with self._lock:
                self._pending = max(0, self._pending - 1)
                stale = epoch != self._epoch
            self._settle()
            if stale:
                return
            self._fail(FollowGoalState.FAILED, f"navigation goal failed: {error}")
            return

        if handle is None:
            with self._lock:
                self._pending = max(0, self._pending - 1)
                if epoch == self._epoch:
                    self._state = FollowGoalState.FAILED
                    self._reason = "navigation returned no goal handle"
            self._settle()
            return

        with self._lock:
            self._pending = max(0, self._pending - 1)
            stale = epoch != self._epoch
            if handle.accepted and not stale:
                self._handles.append(handle)
                self._state = FollowGoalState.ACTIVE
            elif not stale:
                self._state = FollowGoalState.FAILED
                self._reason = "navigation goal rejected"

        if not handle.accepted:
            self._settle()
            return
        if stale:
            self._cancel_handles([handle])
            self._settle()
            return
        handle.get_result_async().add_done_callback(lambda result_future: self._on_result(result_future, handle, epoch))

    def _on_result(self, future: Future, handle: _GoalHandle, epoch: int) -> None:
        try:
            response = future.result()
            status = response.status if response is not None else GoalStatus.STATUS_UNKNOWN
        except Exception as error:  # noqa: BLE001 — action transport failures must terminate motion
            self._finish_handle(handle)
            with self._lock:
                stale = epoch != self._epoch
            if stale:
                return
            self._fail(FollowGoalState.FAILED, f"navigation result lost: {error}")
            return

        self._finish_handle(handle)
        with self._lock:
            if epoch != self._epoch or self._handles or self._pending:
                return
            if status == GoalStatus.STATUS_SUCCEEDED:
                self._state = FollowGoalState.IDLE
                return
            if status == GoalStatus.STATUS_CANCELED:
                self._state = FollowGoalState.FAILED
                self._reason = "navigation goal canceled unexpectedly"
                return
            self._state = FollowGoalState.FAILED
            self._reason = f"navigation ended with status {status}"

    def _finish_handle(self, handle: _GoalHandle) -> None:
        with self._lock:
            self._handles = [candidate for candidate in self._handles if candidate is not handle]

    def _cancel_handles(self, handles: list[_GoalHandle]) -> None:
        with self._lock:
            self._canceling += len(handles)
        for handle in handles:
            self._send_cancel(handle)

    def _send_cancel(self, handle: _GoalHandle) -> None:
        try:
            handle.cancel_goal_async().add_done_callback(self._on_cancel)
        except Exception as error:  # noqa: BLE001 — log a rejected transport-level cancel
            self._logger.error(f"Failed to cancel person-follow goal: {error}")
            with self._lock:
                self._canceling = max(0, self._canceling - 1)
            self._settle()

    def _on_cancel(self, future: Future) -> None:
        try:
            response = future.result()
            if response is not None and not response.goals_canceling:
                self._logger.error("Nav2 rejected person-follow cancellation")
        except Exception as error:  # noqa: BLE001 — cancellation failures must remain visible
            self._logger.error(f"Person-follow cancellation failed: {error}")
        with self._lock:
            self._canceling = max(0, self._canceling - 1)
        self._settle()

    def _settle(self) -> None:
        destroy_client = False
        with self._lock:
            settled = self._pending == 0 and self._canceling == 0
            if settled and self._state is FollowGoalState.CANCELING:
                self._state = FollowGoalState.IDLE
            if settled and self._closed and not self._client_destroyed:
                self._client_destroyed = True
                destroy_client = True
        if destroy_client:
            self._client.destroy()

    def _fail(self, state: FollowGoalState, reason: str) -> None:
        self.cancel(reason)
        with self._lock:
            self._state = state
            self._reason = reason
