"""Gauge_040 from the Workshop map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="workshop_gauge_040",
    label="?",
    title="Gauge 040",
    mesh="../objects/workshop_gauge_040.stl",
    collision="cylinder",
    size=(0.02, 0.0575),
    rgba=(0.1725, 0.4157, 0.7765, 1.0),
    rest_z=0.0575,
    drop_z=0.0675,
)
