"""Gauge_070 from the Workshop map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="workshop_gauge_070",
    label="🥫",
    title="Medium oil can",
    mesh="../objects/workshop_gauge_070.obj",
    viewer={"glb": "/models/workshop/workshop_gauge_070.glb", "preNormalized": True},
    collision="cylinder",
    size=(0.035, 0.0575),
    rgba=(0.1725, 0.4157, 0.7765, 1.0),
    initial_pose=(-2.16, -2.4, 0),
    rest_z=0.0575,
    drop_z=0.0675,
)
