"""Mug_Hidden from the Workshop map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="workshop_mug_hidden",
    label="☕",
    title="Mug Hidden",
    mesh="../objects/workshop_mug_hidden.stl",
    collision="cylinder",
    size=(0.0425, 0.0475),
    rgba=(0.902, 0.7294, 0.2431, 1.0),
    rest_z=0.0475,
    drop_z=0.0575,
)
