"""Target_12 from the Workshop map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="workshop_target_12",
    label="🥫",
    title="Paint can — 12 cm bench",
    mesh="../objects/workshop_target_12.obj",
    viewer={"glb": "/models/workshop/workshop_target_12.glb", "preNormalized": True},
    collision="cylinder",
    size=(0.033, 0.0575),
    # The fallback colour matches the texture (blue, as the brief says): it is
    # what the browser draws until the model loads.
    rgba=(0.1725, 0.4157, 0.7765, 1.0),
    initial_pose=(-1.5, 2.3, 0),
    rest_z=0.0575,
    drop_z=0.1875,
)
