"""Target_30 from the Workshop map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="workshop_target_30",
    label="?",
    title="Target 30",
    mesh="../objects/workshop_target_30.stl",
    collision="cylinder",
    size=(0.033, 0.0575),
    rgba=(0.7882, 0.2275, 0.1882, 1.0),
    rest_z=0.0575,
    drop_z=0.3675,
)
