"""Mug_Kitchen from the Household map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="household_mug_kitchen",
    label="☕",
    title="Mug Kitchen",
    mesh="../objects/household_mug_kitchen.stl",
    mesh_scale=0.5882,
    collision="cylinder",
    size=(0.0250, 0.0279),
    # Blue, not near-white (0.969, 0.965, 0.953): a WHITE mug on the white
    # kitchen floor of an apartment whose walls, floors and half the furniture
    # are the same near-white was unresolvable at the robot's 640x480 -- a
    # probe agent that had just aced two other maps could not find the room,
    # let alone the mug, and the live robot scored 0/2. Blue rather than red
    # because the living-room mug was red and the two must never be
    # confusable in a fetch. Brief updated to match. Post-dates the Aug 16
    # live run.
    rgba=(0.17, 0.42, 0.78, 1.0),
    rest_z=0.0279,
    drop_z=0.9375,
)
