"""Cup_Red from the Counter map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="counter_cup_red",
    label="?",
    title="Cup Red",
    mesh="../objects/counter_cup_red.stl",
    mesh_scale=0.6410,
    collision="cylinder",
    size=(0.0250, 0.0263),
    # (0.80, 0.12, 0.12): actually red. The original (0.698, 0.31, 0.19) is
    # terracotta -- hue ~14 deg -- and two independent probe agents looking at
    # the rendered scene both called it ORANGE and reported "there is no red
    # cup" on a challenge whose brief names "the red cup". An object that is
    # the answer key for a colour question must be the colour it is named.
    # NOTE: changed after the Aug 16 live run -- live scores predate this.
    rgba=(0.80, 0.12, 0.12, 1.0),
    rest_z=0.0314,
    drop_z=0.299,
)
