"""Jar_Jam from the Counter map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="counter_jar_jam",
    label="?",
    title="Jar Jam",
    mesh="../objects/counter_jar_jam.stl",
    mesh_scale=0.5814,
    collision="cylinder",
    size=(0.0250, 0.0314),
    rgba=(0.698, 0.3059, 0.1882, 1.0),
    rest_z=0.0314,
    drop_z=0.194,
)
