"""Teapot from the Counter map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="counter_teapot",
    label="☕",
    title="Teapot",
    mesh="../objects/counter_teapot.obj",
    viewer={"glb": "/models/counter/counter_teapot.glb", "preNormalized": True},
    collision="cylinder",
    size=(0.075, 0.055),
    rgba=(0.1804, 0.3608, 0.2588, 1.0),
    initial_pose=(-2.1, -0.3, 0),
    rest_z=0.055,
    drop_z=0.455,
)
