"""Teapot_Brew from the Counter map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="counter_teapot_brew",
    label="?",
    title="Teapot Brew",
    mesh="../objects/counter_teapot_brew.stl",
    collision="cylinder",
    size=(0.075, 0.055),
    rgba=(0.2902, 0.3137, 0.3373, 1.0),
    rest_z=0.055,
    drop_z=0.305,
)
