workspace: ros2_ws

defaults:
  git_ref: main
  git_recursive: true
  run_rosdep: true

colcon_args:
  - --symlink-install
  - --cmake-args
  - -DUSE_NVTX=OFF

models:
  - name: fast_foundation_stereo
    enabled: true
    upstream_model_repo: https://github.com/NVlabs/Fast-FoundationStereo.git
    source:
      type: git
      url: https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_dnn_stereo_depth.git
      ref: release-4.5
      recursive: true
    checkout_dir: ros2_ws/src/third_party/stereo_models/isaac_ros_dnn_stereo_depth
    ros_packages:
      - isaac_ros_foundationstereo
      - isaac_ros_dnn_stereo_decoder
      - isaac_ros_foundationstereo_models_install
    colcon_packages:
      - isaac_ros_foundationstereo
    executables:
      - package: isaac_ros_foundationstereo
        executable: isaac_ros_foundationstereo_visualizer.py
      - package: isaac_ros_foundationstereo_models_install
        executable: install_foundationstereo_models.sh

  - name: ess_stereo
    enabled: true
    upstream_model_repo: https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_dnn_stereo_depth.git
    source:
      type: git
      url: https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_dnn_stereo_depth.git
      ref: release-4.5
      recursive: true
    checkout_dir: ros2_ws/src/third_party/stereo_models/isaac_ros_dnn_stereo_depth
    ros_packages:
      - isaac_ros_ess
      - isaac_ros_dnn_stereo_decoder
      - isaac_ros_ess_models_install
    colcon_packages:
      - isaac_ros_ess
    executables:
      - package: isaac_ros_ess
        executable: isaac_ros_ess_visualizer.py
      - package: isaac_ros_ess_models_install
        executable: install_ess_models.sh
