"""Transport-agnostic core of the virtual MARS: headless MuJoCo
physics of the apartment + real mars.urdf, with the two robot cameras
rendered offscreen. node.py wraps this in a ROS 2 node that
impersonates the mars_cam/base drivers; this module has no ROS dependency so
it can be developed and tested anywhere (see sim/sandbox/test_driver_core.py).

Model building (URDF attach with visual meshes, planar base, drive/joint
servos) lives in world.py, shared with the sim/sandbox dev tools.
"""

import io
import math
from pathlib import Path

import mujoco
import numpy as np
from PIL import Image

from . import world
from .constants import CAMERA_FOVY, CAMERA_HEIGHT, CAMERA_WIDTH
from .world import ARM_HOME, SPAWN_X, SPAWN_Y, SPAWN_YAW_DEG

# Stop the base if the last Twist is stale, like a real base watchdog.
CMD_VEL_TIMEOUT_S = 0.5

# name -> (body carrying the camera, URDF-frame forward/up of the lens).
# MuJoCo cameras look down their local -Z with +Y up; _camera_quat converts.
CAMERAS = {
    "main": ("robot_camera_optical_frame", (0, 0, 1), (0, -1, 0)),
    "wrist": ("robot_arm_camera_link", (1, 0, 0), (0, 0, 1)),
}
JPEG_QUALITY = 80  # matches main_camera_driver.cpp
# Post-render ACES tone map approximating sim/viewer's Three.js output
# (ACESFilmicToneMapping); exposure calibrated visually against it.
TONEMAP_EXPOSURE = 2.5

# Arm/head PD servo -- apartmentWorker.ts's tuned defaults (reactive feel),
# torque-clamped; the URDF's per-joint damping=5 caps speed at LIMIT/5 rad/s.
KP_JOINT = 50.0
KD_JOINT = 1.0
EFFORT_LIMIT = 50.0  # N*m


def encode_jpeg(rgb: np.ndarray) -> bytes:
    buf = io.BytesIO()
    Image.fromarray(rgb).save(buf, "JPEG", quality=JPEG_QUALITY)
    return buf.getvalue()


def _build_tonemap_lut() -> np.ndarray:
    linear = (np.arange(256, dtype=np.float32) / 255.0) ** 2.2 * TONEMAP_EXPOSURE
    mapped = np.clip(linear * (2.51 * linear + 0.03) / (linear * (2.43 * linear + 0.59) + 0.14), 0, 1)
    return (mapped ** (1 / 2.2) * 255).astype(np.uint8)


# The map is per-channel uint8 -> uint8, so a 256-entry LUT replaces two pow()
# passes over every pixel of every frame.
_TONEMAP_LUT = _build_tonemap_lut()


def _tonemap(rgb: np.ndarray) -> np.ndarray:
    return _TONEMAP_LUT[rgb]


def _camera_quat(forward, up) -> np.ndarray:
    z = -np.array(forward, dtype=float)
    y = np.array(up, dtype=float)
    x = np.cross(y, z)
    quat = np.zeros(4)
    mujoco.mju_mat2Quat(quat, np.column_stack([x, y, z]).flatten())
    return quat


# Apartment meshes (decomposed hulls + textured rooms), generated by
# sim/tools -- see world.default_assets_dir (VIRTUAL_MARS_ASSETS overrides).
ASSETS_DIR = world.default_assets_dir()


class VirtualMars:
    def __init__(
        self,
        split_dir: Path | None = None,
        render_wh: tuple[int, int] | None = None,
        depth_render_wh: tuple[int, int] | None = None,
    ):
        # render_wh / depth_render_wh override the offscreen render
        # resolutions (default: the camera-native CAMERA_WIDTH x
        # CAMERA_HEIGHT). The ROS driver renders RGB at half res and depth at
        # the pointcloud's native res -- software-GL cost scales with fill
        # rate -- and upscales at the wire; direct/notebook users keep full res.
        self._render_w, self._render_h = render_wh or (CAMERA_WIDTH, CAMERA_HEIGHT)
        self._depth_w, self._depth_h = depth_render_wh or (self._render_w, self._render_h)
        rooms = world.find_decomposed_rooms(split_dir or ASSETS_DIR / "apartment_split_v2")
        if not rooms:
            raise RuntimeError(
                f"no decomposed rooms under {split_dir or ASSETS_DIR} -- "
                "run decompose_rooms.py or set VIRTUAL_MARS_ASSETS"
            )
        visual_dir = ASSETS_DIR / "apartment_visual"
        visual_rooms = world.find_visual_rooms(visual_dir) if visual_dir.is_dir() else {}

        world_spec = mujoco.MjSpec.from_string(
            world.build_world_xml(rooms, include_placeholder_robot=False, visual_rooms=visual_rooms)
        )
        # Lidar rays hit only the textured visual meshes (true surfaces, like
        # a real lidar) when available -- without them, fall back to all
        # groups (the collision hulls, ~1cm inflated).
        self._lidar_groups = None
        if visual_rooms:
            self._lidar_groups = np.zeros(6, dtype=np.uint8)
            self._lidar_groups[world.VISUAL_GROUP] = 1
        robot_spec = world.load_robot_spec(world.default_urdf_path())
        world.add_planar_base(robot_spec)
        world_spec.attach(robot_spec, frame=world_spec.worldbody.add_frame(), prefix="robot_")

        for cam_name, (body_name, forward, up) in CAMERAS.items():
            cam = world_spec.body(body_name).add_camera()
            cam.name = cam_name
            cam.fovy = CAMERA_FOVY
            cam.quat = _camera_quat(forward, up)

        self.model = world_spec.compile()
        world.style_robot_geoms(self.model)
        # The planar base pins z at the plane, so the ground's 7mm contact
        # margin reads as permanent penetration -- huge normal force whose
        # friction cone glues the base. The worker's ground has no margin.
        self.model.geom("ground").margin = 0.0
        # znear is a fraction of stat.extent; pin it to 0.03m (the viewer's
        # camera near plane) so the cameras clip their own housing shells
        # instead of rendering them.
        self.model.vis.map.znear = 0.03 / self.model.stat.extent
        # The textured rooms carry baked lighting; brighten toward the
        # Three.js render (ambient 1.2 + ACES exposure 1.5 there).
        self.model.vis.headlight.ambient[:] = 0.5
        self.model.vis.headlight.diffuse[:] = 0.5
        self.data = mujoco.MjData(self.model)

        self._base_id = self.model.body("robot_base_link").id
        self._base = {}  # "x"/"y"/"yaw" -> (qpos_adr, dof_adr)
        for short in ("x", "y", "yaw"):
            jid = self.model.joint(f"robot_base_{short}").id
            self._base[short] = (self.model.jnt_qposadr[jid], self.model.jnt_dofadr[jid])

        self._joints = {}  # name -> (qpos_adr, dof_adr, home)
        for name, home in ARM_HOME.items():
            jid = self.model.joint(f"robot_{name}").id
            self._joints[name] = (self.model.jnt_qposadr[jid], self.model.jnt_dofadr[jid], home)
        mimic_name, mimic_source, mimic_mult = world.MIMIC_JOINT
        jid = self.model.joint(f"robot_{mimic_name}").id
        self._mimic = (self.model.jnt_qposadr[jid], self.model.jnt_dofadr[jid], mimic_source, mimic_mult)

        self._renderer: mujoco.Renderer | None = None
        self._depth_renderer: mujoco.Renderer | None = None
        self._cmd_vx = 0.0
        self._cmd_wz = 0.0
        self._cmd_sim_time = -math.inf
        self.reset()

    def reset(self) -> None:
        mujoco.mj_resetData(self.model, self.data)
        self.data.qpos[self._base["x"][0]] = SPAWN_X
        self.data.qpos[self._base["y"][0]] = SPAWN_Y
        self.data.qpos[self._base["yaw"][0]] = math.radians(SPAWN_YAW_DEG)
        for qadr, _dadr, home in self._joints.values():
            self.data.qpos[qadr] = home
        mq, _md, source, mult = self._mimic
        self.data.qpos[mq] = mult * ARM_HOME[source]
        self._cmd_vx = self._cmd_wz = 0.0
        self._cmd_sim_time = -math.inf
        mujoco.mj_forward(self.model, self.data)

    def set_cmd_vel(self, vx: float, wz: float) -> None:
        self._cmd_vx = max(-world.MAX_LINEAR, min(world.MAX_LINEAR, vx))
        self._cmd_wz = max(-world.MAX_YAW, min(world.MAX_YAW, wz))
        self._cmd_sim_time = self.data.time

    def set_joint_target(self, name: str, value: float) -> None:
        if name in self._joints:
            qadr, dadr, _home = self._joints[name]
            self._joints[name] = (qadr, dadr, value)

    def joint_targets(self) -> dict[str, float]:
        return {name: target for name, (_q, _d, target) in self._joints.items()}

    def step(self, duration: float) -> None:
        """Advance the sim by `duration` seconds, applying servos each step."""
        end = self.data.time + duration
        while self.data.time < end:
            self._apply_control()
            mujoco.mj_step(self.model, self.data)
            if not np.all(np.isfinite(self.data.qpos)):
                self.reset()
                return

    def _apply_control(self) -> None:
        d = self.data
        dof_x, dof_y, dof_yaw = (self._base[k][1] for k in ("x", "y", "yaw"))

        lin = math.hypot(d.qvel[dof_x], d.qvel[dof_y])
        if lin > world.MAX_BASE_LINEAR_SPEED:
            d.qvel[dof_x] *= world.MAX_BASE_LINEAR_SPEED / lin
            d.qvel[dof_y] *= world.MAX_BASE_LINEAR_SPEED / lin
        if abs(d.qvel[dof_yaw]) > world.MAX_BASE_ANGULAR_SPEED:
            d.qvel[dof_yaw] = math.copysign(world.MAX_BASE_ANGULAR_SPEED, d.qvel[dof_yaw])

        expired = d.time - self._cmd_sim_time > CMD_VEL_TIMEOUT_S
        vx = 0.0 if expired else self._cmd_vx
        wz = 0.0 if expired else self._cmd_wz

        yaw = d.qpos[self._base["yaw"][0]]
        cos, sin = math.cos(yaw), math.sin(yaw)
        v_forward = d.qvel[dof_x] * cos + d.qvel[dof_y] * sin
        v_lateral = -d.qvel[dof_x] * sin + d.qvel[dof_y] * cos

        force_forward = world.KP_FORWARD * (vx - v_forward)
        force_lateral = -world.KP_LATERAL * v_lateral
        torque_yaw = world.KP_YAW * (wz - d.qvel[dof_yaw])
        d.xfrc_applied[self._base_id, 0] = force_forward * cos - force_lateral * sin
        d.xfrc_applied[self._base_id, 1] = force_forward * sin + force_lateral * cos
        d.xfrc_applied[self._base_id, 5] = torque_yaw

        for qadr, dadr, target in self._joints.values():
            torque = KP_JOINT * (target - d.qpos[qadr]) - KD_JOINT * d.qvel[dadr]
            d.qfrc_applied[dadr] = max(-EFFORT_LIMIT, min(EFFORT_LIMIT, torque))
        mq, md, source, mult = self._mimic
        target = mult * self._joints[source][2]
        torque = KP_JOINT * (target - d.qpos[mq]) - KD_JOINT * d.qvel[md]
        d.qfrc_applied[md] = max(-EFFORT_LIMIT, min(EFFORT_LIMIT, torque))

    def update_camera(self, camera: str) -> None:
        """Snapshot sim state into the renderer's scene (fast; call under the
        physics lock). The GL render itself (read_rgb) can then run outside."""
        if self._renderer is None:
            self._renderer = mujoco.Renderer(self.model, height=self._render_h, width=self._render_w)
        self._renderer.update_scene(self.data, camera=camera)
        # Shadows/reflections cost ~3x on software GL (242 -> 71 ms/frame).
        self._renderer.scene.flags[mujoco.mjtRndFlag.mjRND_SHADOW] = 0
        self._renderer.scene.flags[mujoco.mjtRndFlag.mjRND_REFLECTION] = 0

    def read_rgb(self) -> np.ndarray:
        """Tone-mapped uint8 RGB of the last update_camera snapshot. Slow
        (software GL) -- do not hold the physics lock across this."""
        return _tonemap(self._renderer.render())

    def render_rgb(self, camera: str) -> np.ndarray:
        self.update_camera(camera)
        return self.read_rgb()

    def render_jpeg(self, camera: str) -> bytes:
        return encode_jpeg(self.render_rgb(camera))

    def update_depth(self, camera: str) -> None:
        """Depth counterpart of update_camera. The robot's own geoms (group 0)
        are excluded: the real stereo pipeline can't resolve the arm/head that
        close to the lens (max_disparity limit + edge/speckle filters), so the
        robot never appears in its own depth -- without this, STVL marks the
        arm as an obstacle at the footprint and Nav2 can't plan."""
        if self._depth_renderer is None:
            self._depth_renderer = mujoco.Renderer(self.model, height=self._depth_h, width=self._depth_w)
            self._depth_renderer.enable_depth_rendering()
            self._depth_scene_option = mujoco.MjvOption()
            self._depth_scene_option.geomgroup[0] = 0
        self._depth_renderer.update_scene(self.data, camera=camera, scene_option=self._depth_scene_option)

    def read_depth(self) -> np.ndarray:
        return self._depth_renderer.render()

    def render_depth(self, camera: str) -> np.ndarray:
        """Depth image in meters (float32, render height x width)."""
        self.update_depth(camera)
        return self.read_depth()

    def lidar_scan(self, n_rays: int, max_range: float) -> np.ndarray:
        """360-degree planar scan from the base_laser mount, CCW from the
        robot's +x. Distances in meters; max_range where nothing was hit."""
        body_id = self.model.body("robot_base_laser").id
        origin = self.data.xpos[body_id].copy()
        _x, _y, yaw = self.pose()
        angles = yaw + np.arange(n_rays) * (2 * math.pi / n_rays)
        vecs = np.zeros((n_rays, 3))
        vecs[:, 0] = np.cos(angles)
        vecs[:, 1] = np.sin(angles)

        geomids = np.full(n_rays, -1, dtype=np.int32)
        dists = np.full(n_rays, -1.0)
        mujoco.mj_multiRay(
            self.model,
            self.data,
            origin,
            vecs.flatten(),
            self._lidar_groups,
            1,  # include static geoms
            self._base_id,  # exclude the robot's own base body
            geomids,
            dists,
            None,  # surface normals not needed
            n_rays,
            max_range,
        )
        dists[geomids == -1] = max_range
        return np.minimum(dists, max_range)

    def occupancy_grid(self, resolution: float = 0.05) -> tuple[np.ndarray, float, float]:
        """Rasterize the collision world into a nav occupancy grid (values
        -1/0/100, row-major from the origin cell); returns (grid, origin_x,
        origin_y). Occupied = static collision triangles clipped to the
        robot-height slab and projected (height-exact: a probe-ray scheme
        loses any wall taller than the probe start). Free vs unknown =
        downward floor rays, with the robot parked out of bounds."""
        wall_min, wall_top = 0.10, 1.4  # above rugs/thresholds; below ceilings

        # Apartment bounds from its geoms' bounding spheres.
        apt = self.model.body("apartment").id
        geom_ids = [i for i in range(self.model.ngeom) if self.model.geom_bodyid[i] == apt]
        mujoco.mj_forward(self.model, self.data)
        centers = self.data.geom_xpos[geom_ids]
        radii = self.model.geom_rbound[geom_ids]
        xmin, ymin = (centers[:, :2] - radii[:, None]).min(axis=0) - 0.3
        xmax, ymax = (centers[:, :2] + radii[:, None]).max(axis=0) + 0.3

        # Park the robot outside the map so the floor rays don't see it.
        saved = self.data.qpos.copy()
        self.data.qpos[self._base["x"][0]] = xmax + 50.0
        mujoco.mj_forward(self.model, self.data)

        width = int(np.ceil((xmax - xmin) / resolution))
        height = int(np.ceil((ymax - ymin) / resolution))
        xs = xmin + (np.arange(width) + 0.5) * resolution
        ys = ymin + (np.arange(height) + 0.5) * resolution
        gx, gy = np.meshgrid(xs, ys)  # row-major: y rows, x cols
        n = width * height

        grid = np.full(n, -1, dtype=np.int8)
        origins = np.column_stack([gx.ravel(), gy.ravel(), np.full(n, wall_top)])
        # mj_multiRay shares one origin, so cast per cell (one-time, ~40k rays, ~1s).
        geomid_out = np.zeros(1, dtype=np.int32)
        down = np.array([0.0, 0.0, -1.0])
        for i in range(n):
            d = mujoco.mj_ray(self.model, self.data, origins[i], down, None, 1, -1, geomid_out)
            if geomid_out[0] != -1 and d >= 0:
                grid[i] = 0  # something below: inside the world
        grid = grid.reshape(height, width)
        grid[self._rasterize_static_slab(wall_min, wall_top, xmin, ymin, width, height, resolution)] = 100

        self.data.qpos[:] = saved
        mujoco.mj_forward(self.model, self.data)
        return grid, float(xmin), float(ymin)

    def lidar_occupancy_grid(
        self,
        resolution: float = 0.05,
        origin_stride_m: float = 0.4,
        n_rays: int = 720,
        max_range: float = 12.0,
    ) -> tuple[np.ndarray, float, float]:
        """Rasterize the world the way the robot's own lidar would map it --
        a virtual SLAM pass with perfect poses. Horizontal rays are cast at
        the laser mount height against the same visual surfaces lidar_scan()
        hits, from a grid of reachable floor positions; beams clear free
        space, endpoints mark obstacles, everything unseen stays unknown.

        This is the nav map that keeps AMCL consistent: a real robot
        localizes against a map made BY its lidar, so at shin height a couch
        is legs and a gap, not the solid footprint occupancy_grid() rasterizes
        from collision geometry. Returns (grid, origin_x, origin_y) like
        occupancy_grid()."""
        # Reachable-floor candidates for scan origins (also fixes the bounds).
        base_grid, xmin, ymin = self.occupancy_grid(resolution)
        height, width = base_grid.shape

        # True laser height above the floor, from the model itself.
        mujoco.mj_forward(self.model, self.data)
        laser_z = float(self.data.xpos[self.model.body("robot_base_laser").id][2])

        # Park the robot far away so rays never hit it.
        saved = self.data.qpos.copy()
        self.data.qpos[self._base["x"][0]] += 100.0
        mujoco.mj_forward(self.model, self.data)

        try:
            stride = max(1, int(round(origin_stride_m / resolution)))
            rows, cols = np.nonzero(base_grid == 0)
            pick = (rows % stride == 0) & (cols % stride == 0)
            origin_xy = np.column_stack(
                [xmin + (cols[pick] + 0.5) * resolution, ymin + (rows[pick] + 0.5) * resolution]
            )

            angles = np.arange(n_rays) * (2.0 * math.pi / n_rays)
            vecs = np.zeros((n_rays, 3))
            vecs[:, 0] = np.cos(angles)
            vecs[:, 1] = np.sin(angles)
            step = resolution * 0.9
            ts = (np.arange(int(max_range / step)) + 0.5) * step  # sample offsets along a beam

            def cells(x: np.ndarray, y: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
                c = ((x - xmin) / resolution).astype(np.int64)
                r = ((y - ymin) / resolution).astype(np.int64)
                ok = (c >= 0) & (c < width) & (r >= 0) & (r < height)
                return r[ok], c[ok]

            seen_free = np.zeros((height, width), dtype=bool)
            seen_occ = np.zeros((height, width), dtype=bool)
            geomids = np.full(n_rays, -1, dtype=np.int32)
            dists = np.full(n_rays, -1.0)
            for ox, oy in origin_xy:
                origin = np.array([ox, oy, laser_z])
                geomids.fill(-1)
                dists.fill(-1.0)
                mujoco.mj_multiRay(
                    self.model,
                    self.data,
                    origin,
                    vecs.flatten(),
                    self._lidar_groups,
                    1,
                    self._base_id,
                    geomids,
                    dists,
                    None,
                    n_rays,
                    max_range,
                )
                hit = (geomids != -1) & (dists >= 0)
                if not hit.any():
                    continue
                d = dists[hit]
                dirs = vecs[hit, :2]
                # Clear along each beam, stopping one cell short of the surface.
                mask = ts[None, :] < (d - resolution)[:, None]
                px = ox + (dirs[:, 0:1] * ts[None, :])[mask]
                py = oy + (dirs[:, 1:2] * ts[None, :])[mask]
                r, c = cells(px, py)
                seen_free[r, c] = True
                # Endpoints are the surfaces the lidar actually returns from.
                r, c = cells(ox + dirs[:, 0] * d, oy + dirs[:, 1] * d)
                seen_occ[r, c] = True
        finally:
            # Restore even if a ray call raises: a leaked parked pose would
            # corrupt every later scan/step on this instance.
            self.data.qpos[:] = saved
            mujoco.mj_forward(self.model, self.data)

        grid = np.full((height, width), -1, dtype=np.int8)
        grid[seen_free] = 0
        grid[seen_occ] = 100  # occupied wins over any grazing clear
        return grid, float(xmin), float(ymin)

    def _rasterize_static_slab(
        self, zlo: float, zhi: float, xmin: float, ymin: float, width: int, height: int, resolution: float
    ) -> np.ndarray:
        """Boolean (height, width) mask of cells touched by static collision
        triangles within the z-slab [zlo, zhi] (clipped before projecting)."""
        from PIL import ImageDraw

        robot_bodies = set()
        for b in range(self.model.nbody):
            parent = b
            while parent != 0:
                if parent == self._base_id:
                    robot_bodies.add(b)
                    break
                parent = self.model.body_parentid[parent]

        polys: list[np.ndarray] = []
        for g in range(self.model.ngeom):
            if self.model.geom_type[g] != mujoco.mjtGeom.mjGEOM_MESH:
                continue  # the only non-mesh static geom is the ground plane
            if self.model.geom_bodyid[g] in robot_bodies:
                continue
            did = self.model.geom_dataid[g]
            vadr, vnum = self.model.mesh_vertadr[did], self.model.mesh_vertnum[did]
            fadr, fnum = self.model.mesh_faceadr[did], self.model.mesh_facenum[did]
            verts = self.model.mesh_vert[vadr : vadr + vnum]
            faces = self.model.mesh_face[fadr : fadr + fnum]
            world_verts = verts @ self.data.geom_xmat[g].reshape(3, 3).T + self.data.geom_xpos[g]
            tris = world_verts[faces]  # (nf, 3, 3)
            zs = tris[:, :, 2]
            polys.extend(tris[(zs.max(axis=1) > zlo) & (zs.min(axis=1) < zhi)])

        def clip_z(poly: np.ndarray, z: float, keep_above: bool) -> np.ndarray:
            """Sutherland-Hodgman against one z-plane."""
            sign = 1.0 if keep_above else -1.0
            out: list[np.ndarray] = []
            for i in range(len(poly)):
                a, b = poly[i], poly[(i + 1) % len(poly)]
                da, db = sign * (a[2] - z), sign * (b[2] - z)
                if da >= 0:
                    out.append(a)
                if (da >= 0) != (db >= 0):
                    out.append(a + (b - a) * (da / (da - db)))
            return np.asarray(out)

        mask_img = Image.new("L", (width, height), 0)
        draw = ImageDraw.Draw(mask_img)
        for tri in polys:
            poly = clip_z(clip_z(tri, zlo, True), zhi, False)
            if len(poly) < 2:
                continue
            px = [((x - xmin) / resolution, (y - ymin) / resolution) for x, y, _z in poly]
            if len(px) == 2:
                draw.line(px, fill=255, width=1)
            else:
                draw.polygon(px, fill=255, outline=255)
        return np.asarray(mask_img) > 0

    def pose(self) -> tuple[float, float, float]:
        return (
            float(self.data.qpos[self._base["x"][0]]),
            float(self.data.qpos[self._base["y"][0]]),
            float(self.data.qpos[self._base["yaw"][0]]),
        )

    def velocity(self) -> tuple[float, float, float]:
        """(v_forward, v_lateral, wz) in the base frame, for odometry."""
        dof_x, dof_y, dof_yaw = (self._base[k][1] for k in ("x", "y", "yaw"))
        yaw = self.data.qpos[self._base["yaw"][0]]
        cos, sin = math.cos(yaw), math.sin(yaw)
        vx, vy = self.data.qvel[dof_x], self.data.qvel[dof_y]
        return (vx * cos + vy * sin, -vx * sin + vy * cos, float(self.data.qvel[dof_yaw]))

    def head_pitch_deg(self) -> float:
        qadr, _dadr, _t = self._joints["joint_head"]
        return math.degrees(float(self.data.qpos[qadr]))

    def joint_positions(self) -> dict[str, float]:
        return {name: float(self.data.qpos[qadr]) for name, (qadr, _d, _t) in self._joints.items()}
