"""MuJoCo world construction for the virtual MARS: apartment collision hulls
+ textured visual rooms + the real mars.urdf with a planar base. One
implementation shared by the driver node and the native dev sandboxes
(sim/sandbox).

Assets (decomposed hulls, textured rooms) are generated by sim/tools and read
from VIRTUAL_MARS_ASSETS (default: <repo>/sim/assets in a dev checkout).
"""

import math
import os
from pathlib import Path

import mujoco

# Matches sim/viewer's spawn (scene.ts SPAWN_*) and the webapp map origin.
SPAWN_X = -4.34
SPAWN_Y = -0.17
SPAWN_YAW_DEG = -89.8

# Base drive gains -- ported from the webapp worker lineage (KP_YAW=6
# resonates with the arm servos on the same axis; 3 is the verified-stable
# value, see sim/viewer's apartmentWorker.ts).
KP_FORWARD = 200.0
KP_LATERAL = 40.0
KP_YAW = 3.0

MAX_LINEAR = 0.4
MAX_YAW = 1.0

# Safety governor against imperfect hull-seam contacts (see sim/sandbox
# README): clamp base velocity so a bad single-step impulse is a recoverable
# thump, not NaN.
MAX_BASE_LINEAR_SPEED = 2.0
MAX_BASE_ANGULAR_SPEED = 6.0

DRIVEN_JOINTS = ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6", "joint_head"]
MIMIC_JOINT = ("joint6M", "joint6", -1.0)  # (name, source, multiplier)

# Matches the webapp's ARM_HOME_POSITIONS.
ARM_HOME = {
    "joint1": 1.445009902188274,
    "joint2": -1.3882526130365052,
    "joint3": 1.517106999218899,
    "joint4": 0.44638840927472156,
    "joint5": -0.08897088569736719,
    "joint6": 0.0015339807878856412,
    "joint_head": 0.0,
}

# Visual conventions matching sim/viewer's Three.js render.
ORANGE_LINKS = {"link1", "link3", "link5"}
BRIGHT_ORANGE = (1.0, 0.5, 0.0, 1.0)
HIDDEN_MARKER_LINKS = {"ee_link", "head_camera_left", "head_camera_right"}
VISUAL_GROUP = 1
COLLISION_GROUP = 3

_PALETTE = [
    "0.9 0.2 0.2 1",
    "0.2 0.7 0.9 1",
    "0.9 0.7 0.1 1",
    "0.3 0.9 0.3 1",
    "0.8 0.3 0.9 1",
    "0.9 0.5 0.2 1",
    "0.2 0.9 0.7 1",
    "0.6 0.6 0.9 1",
]


def repo_root() -> Path:
    """Best-effort repo root for dev checkouts (this file lives at
    ros2_ws/src/mars_bot/mars_sim_driver/mars_sim_driver/world.py)."""
    return Path(__file__).resolve().parents[5]


def default_assets_dir() -> Path:
    env = os.environ.get("VIRTUAL_MARS_ASSETS")
    return Path(env) if env else repo_root() / "sim" / "assets"


def default_urdf_path() -> Path:
    """mars.urdf with its mesh STLs next to it. Prefers the installed
    mars_sim package share (the same file the real bringup feeds
    robot_state_publisher); falls back to the source tree for non-ROS use
    (sandboxes, tests)."""
    try:
        from ament_index_python.packages import get_package_share_directory

        return Path(get_package_share_directory("mars_sim")) / "urdf" / "mars.urdf"
    except Exception:
        return repo_root() / "ros2_ws" / "src" / "mars_bot" / "mars_sim" / "urdf" / "mars.urdf"


def find_decomposed_rooms(split_dir: Path) -> dict[str, list[Path]]:
    """{room_name: [collision piece paths]} under split_dir (see sim/tools)."""
    rooms: dict[str, list[Path]] = {}
    if not split_dir.is_dir():
        return rooms
    for room_dir in sorted(p for p in split_dir.iterdir() if p.is_dir()):
        pieces = sorted(room_dir.glob(f"{room_dir.name}_collision_*.obj"))
        if pieces:
            rooms[room_dir.name] = pieces
    return rooms


def find_visual_rooms(visual_dir: Path) -> dict[str, Path]:
    """{room_name: obj_path} for the textured rooms sim/tools exported."""
    rooms: dict[str, Path] = {}
    if not visual_dir.is_dir():
        return rooms
    for room_dir in sorted(p for p in visual_dir.iterdir() if p.is_dir()):
        obj_path = room_dir / f"{room_dir.name}.obj"
        if obj_path.exists():
            rooms[room_dir.name] = obj_path
    return rooms


def spawn_camera_view(x: float, y: float, yaw_deg: float) -> tuple[float, float, float, float, float, float]:
    """(lookat_xyz, azimuth, elevation, extent) for MJCF <statistic>/<visual>,
    matching sim/viewer's chase-cam framing at spawn."""
    chase_distance, chase_height, target_height = 1.8, 1.1, 0.5
    yaw = math.radians(yaw_deg)
    eye = (x - math.cos(yaw) * chase_distance, y - math.sin(yaw) * chase_distance, chase_height)
    lookat = (x, y, target_height)
    delta = tuple(a - b for a, b in zip(lookat, eye, strict=False))
    distance = math.sqrt(sum(c * c for c in delta))
    forward = tuple(c / distance for c in delta)
    elevation_deg = math.degrees(math.asin(forward[2]))
    azimuth_deg = math.degrees(math.atan2(forward[1], forward[0]))
    return lookat[0], lookat[1], lookat[2], azimuth_deg, elevation_deg, distance / 1.5


def capped_texture_path(png_path: Path, texture_max: int) -> Path:
    """Path to a cached downscaled copy of png_path (longest side <=
    texture_max), generated next to the original on first use.

    The baked-lighting atlases ship at 4096x4096 (~50MB decoded); the model
    keeps that in RAM and every GL renderer context uploads it AGAIN -- under
    software GL that is process memory too, so each atlas is paid up to three
    times for cameras that output 640x480 at most. Falls back to the original
    when the cache can't be written (read-only assets dir)."""
    from PIL import Image  # deferred: keep `import world` light for the sandbox tools

    with Image.open(png_path) as im:
        if max(im.size) <= texture_max:
            return png_path
        scale = texture_max / max(im.size)
        new_size = (max(1, round(im.width * scale)), max(1, round(im.height * scale)))
        cached = png_path.with_name(f"{png_path.stem}.cap{texture_max}{png_path.suffix}")
        if cached.exists() and cached.stat().st_mtime >= png_path.stat().st_mtime:
            return cached
        try:
            im.resize(new_size, Image.LANCZOS).save(cached)
        except OSError:
            return png_path
    return cached


def build_world_xml(
    rooms: dict[str, list[Path]],
    include_placeholder_robot: bool = True,
    visual_rooms: dict[str, Path] | None = None,
    texture_max: int | None = None,
) -> str:
    """The apartment environment MJCF (floor plane + decomposed room hulls,
    optionally the textured visual rooms in their own geom group).
    texture_max caps the visual textures' resolution (see capped_texture_path)."""
    collision_group = COLLISION_GROUP if visual_rooms else 0

    mesh_lines = []
    geom_lines = []
    i = 0
    for pieces in rooms.values():
        for piece in pieces:
            mesh_lines.append(f'    <mesh name="m{i}" file="{piece.resolve()}"/>')
            color = _PALETTE[i % len(_PALETTE)]
            # 7mm is the stress-tested margin floor: below it a hull seam
            # corner-catches (see sim/sandbox README).
            geom_lines.append(
                f'      <geom name="{piece.stem}" mesh="m{i}" type="mesh" friction="0.9 0.01 0.001" '
                f'condim="6" margin="0.007" solref="0.02 1" rgba="{color}" group="{collision_group}"/>'
            )
            i += 1

    visual_mesh_lines = []
    visual_geom_lines = []
    for room, obj_path in (visual_rooms or {}).items():
        png_path = obj_path.with_suffix(".png")
        if texture_max:
            png_path = capped_texture_path(png_path, texture_max)
        visual_mesh_lines.append(f'    <mesh name="vis_{room}" file="{obj_path.resolve()}"/>')
        visual_mesh_lines.append(f'    <texture name="tex_{room}" type="2d" file="{png_path.resolve()}"/>')
        visual_mesh_lines.append(f'    <material name="mat_{room}" texture="tex_{room}" specular="0" shininess="0"/>')
        visual_geom_lines.append(
            f'      <geom name="{room}_visual" mesh="vis_{room}" type="mesh" material="mat_{room}" '
            f'contype="0" conaffinity="0" group="{VISUAL_GROUP}"/>'
        )

    robot_body = (
        """
    <body name="robot_base" pos="0 0 0">
      <freejoint name="base_free"/>
      <inertial pos="-0.0587 0 0.0838" mass="3.0" diaginertia="0.03 0.03 0.02"/>
      <geom name="base_collision" type="box" size="0.0939 0.091 0.0838" pos="-0.0587 0 0.0838"
            friction="0.9 0.01 0.001" rgba="0.2 0.6 1 0.9"/>
    </body>"""
        if include_placeholder_robot
        else ""
    )

    lx, ly, lz, azimuth, elevation, extent = spawn_camera_view(SPAWN_X, SPAWN_Y, SPAWN_YAW_DEG)

    return f"""
<mujoco model="apartment">
  <!-- implicitfast damps the single-step impulse spikes hull seams can
       produce -- what makes 1200+ hulls stable at all. -->
  <option timestep="0.002" gravity="0 0 -9.81" integrator="implicitfast"/>
  <visual>
    <global azimuth="{azimuth}" elevation="{elevation}" offwidth="1280" offheight="960"/>
  </visual>
  <statistic center="{lx} {ly} {lz}" extent="{extent}"/>
  <asset>
{chr(10).join(mesh_lines)}
{chr(10).join(visual_mesh_lines)}
  </asset>
  <worldbody>
    <light pos="4 -3 6" dir="-4 3 -6" diffuse="1 1 1"/>
    <light pos="-4 3 3" dir="4 -3 -3" diffuse="0.67 0.8 1"/>
    <geom name="ground" type="plane" size="20 20 0.1" friction="0.9 0.01 0.001" margin="0.007"
          solref="0.01 1" rgba="0.35 0.35 0.35 1" group="{collision_group}"/>
    <body name="apartment" quat="0.7071068 0.7071068 0 0">
{chr(10).join(geom_lines)}
{chr(10).join(visual_geom_lines)}
    </body>{robot_body}
  </worldbody>
</mujoco>
"""


def load_robot_spec(urdf_path: Path) -> mujoco.MjSpec:
    """mars.urdf with <visual> STL meshes intact: MuJoCo's URDF importer
    discards visuals unless the embedded compiler override is present, and it
    can't resolve package:// URIs, so both are rewritten here."""
    pkg_dir = urdf_path.parent if (urdf_path.parent / "meshes").is_dir() else urdf_path.parent.parent
    robot_dir = str(pkg_dir.resolve()) + "/"
    urdf_text = urdf_path.read_text().replace("package://mars_sim/", robot_dir)
    urdf_text = urdf_text.replace(
        '<robot name="mars_bot">',
        '<robot name="mars_bot"><mujoco><compiler discardvisual="false"/></mujoco>',
    )
    return mujoco.MjSpec.from_string(urdf_text)


def add_planar_base(robot_spec: mujoco.MjSpec) -> None:
    """Planar base (x, y, yaw): a wheeled chassis can't pitch, and a free
    joint lets the arm's reaction torque tip the 0.89kg base over."""
    base_body = robot_spec.body("base_link")
    for name, jtype, axis in (
        ("base_x", mujoco.mjtJoint.mjJNT_SLIDE, (1, 0, 0)),
        ("base_y", mujoco.mjtJoint.mjJNT_SLIDE, (0, 1, 0)),
        ("base_yaw", mujoco.mjtJoint.mjJNT_HINGE, (0, 0, 1)),
    ):
        joint = base_body.add_joint()
        joint.name = name
        joint.type = jtype
        joint.axis = axis


def style_robot_geoms(model: mujoco.MjModel, prefix: str = "robot_") -> None:
    """Match sim/viewer's styling: orange arm links, hidden frame markers,
    collision boxes into the hidden group, matt_black lifted to charcoal."""
    for i in range(model.ngeom):
        body_name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_BODY, model.geom_bodyid[i]) or ""
        link_name = body_name.removeprefix(prefix)

        if model.geom_contype[i] == 1:  # a <collision> geom
            model.geom_group[i] = COLLISION_GROUP
        elif link_name in ORANGE_LINKS:
            model.geom_rgba[i] = BRIGHT_ORANGE
        elif link_name in HIDDEN_MARKER_LINKS:
            model.geom_rgba[i, 3] = 0.0
        elif model.geom_rgba[i, :3].mean() < 0.4:
            model.geom_rgba[i, :3] = 0.16
