"""Book_Bed from the Rounds map (generated by sim/tools/roblox_to_innate.py)."""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="rounds_book_bed",
    label="📕",
    title="Book Bed",
    mesh="../objects/rounds_book_bed.stl",
    mesh_scale=0.4854,
    collision="box",
    # A findable book. The original was an 8 mm-thick CREAM wafer on a pale
    # floor: a probe agent searched the bedroom exhaustively for 200 s -- three
    # full rotations, a traverse along the bed, four pick probes -- and never
    # saw it; the live robot also scored 0 here. An object that a competent
    # sighted agent cannot detect from the robot's own camera makes the fetch
    # a lottery, not a task. Tripled thickness (still a thin book) and a
    # saturated red cover. Changed after the Aug 16 live run.
    size=(0.0345, 0.0250, 0.0120),
    rgba=(0.75, 0.15, 0.15, 1.0),
    rest_z=0.0242,
    drop_z=0.497,
)
