"""Pantry benchmark map (generated by sim/tools/roblox_to_innate.py).

Authored in Roblox Studio and exported as primitives -- see that tool's header
for the axis conversion. Decoration is drawn but never collided with.

Structural geometry comes from the exporter. The finish layer below is
hand-authored; it preserves support heights and adds grocery clearance.
"""

from dataclasses import replace

from mars_sim_driver.scene_details import pantry as finish_room
from mars_sim_driver.statics import Geom, Room

ROOM = Room(
    name="pantry",
    title="Pantry",
    spawn=(0.0, -1.45, 90.0),
    geoms=[
    Geom("box", (1.9, 0.7, 0.003), (0.0, -0.1, 0.003), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.4706, 0.4941, 0.5255, 1.0), name="aisle", collide=False),
    Geom("box", (0.025, 0.65, 0.004), (1.8, -0.1, 0.004), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.8078, 0.5804, 0.2118, 1.0), name="aisletick", collide=False),
    Geom("box", (0.025, 0.65, 0.004), (0.0, -0.1, 0.004), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.8078, 0.5804, 0.2118, 1.0), name="aisletick", collide=False),
    Geom("box", (0.025, 0.65, 0.004), (0.9, -0.1, 0.004), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.8078, 0.5804, 0.2118, 1.0), name="aisletick", collide=False),
    Geom("box", (0.025, 0.65, 0.004), (-1.8, -0.1, 0.004), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.8078, 0.5804, 0.2118, 1.0), name="aisletick", collide=False),
    Geom("box", (0.025, 0.65, 0.004), (-0.9, -0.1, 0.004), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.8078, 0.5804, 0.2118, 1.0), name="aisletick", collide=False),
    Geom("box", (2.5, 1.8, 0.03), (0.0, -0.0, 1.33), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.9647, 0.9529, 0.9255, 1.0), name="ceiling", collide=False),
    Geom("box", (0.4, 0.03, 0.004), (-1.5, -1.0, 0.004), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.8078, 0.5804, 0.2118, 1.0), name="deliverymark", collide=False),
    Geom("box", (0.01, 0.55, 0.13), (-2.21, -0.0, 0.62), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.8078, 0.5804, 0.2118, 1.0), name="labela", collide=False),
    Geom("box", (0.55, 0.01, 0.13), (0.0, 1.51, 0.62), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.1882, 0.3608, 0.6588, 1.0), name="labelb", collide=False),
    Geom("box", (0.01, 0.55, 0.13), (2.21, -0.0, 0.62), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.1804, 0.3608, 0.2588, 1.0), name="labelc", collide=False),
    Geom("cylinder", (0.0275, 0.015), (1.5, -0.1, 1.2), quat=(0.0, 0.0, 0.0, 1.0), rgba=(0.9647, 0.9529, 0.9255, 1.0), name="lamp", collide=False),
    Geom("cylinder", (0.0275, 0.015), (0.0, -0.1, 1.2), quat=(0.0, 0.0, 0.0, 1.0), rgba=(0.9647, 0.9529, 0.9255, 1.0), name="lamp", collide=False),
    Geom("cylinder", (0.0275, 0.015), (-1.5, -0.1, 1.2), quat=(0.0, 0.0, 0.0, 1.0), rgba=(0.9647, 0.9529, 0.9255, 1.0), name="lamp", collide=False),
    Geom("box", (2.5, 0.01, 0.05), (0.0, 1.74, 0.05), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.4392, 0.3059, 0.1725, 1.0), name="skirt", collide=False),
    Geom("box", (2.5, 0.01, 0.05), (0.0, -1.74, 0.05), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.4392, 0.3059, 0.1725, 1.0), name="skirt", collide=False),
    Geom("box", (0.25, 0.25, 0.01), (0.0, -1.45, 0.01), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.3608, 0.7765, 0.4549, 1.0), name="startpad", collide=False),
    Geom("box", (2.5, 1.8, 0.05), (0.0, -0.0, -0.05), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.2902, 0.3137, 0.3373, 1.0), name="floor"),
    Geom("box", (0.13, 0.1, 0.008), (2.24, -0.0, 0.268), quat=(0.707107, 0.0, 0.0, -0.707107), rgba=(0.6118, 0.4392, 0.2627, 1.0), name="base"),
    Geom("box", (0.007, 0.086, 0.055), (2.24, -0.123, 0.323), quat=(0.707107, 0.0, 0.0, -0.707107), rgba=(0.6118, 0.4392, 0.2627, 1.0), name="sidee"),
    Geom("box", (0.13, 0.007, 0.055), (2.333, -0.0, 0.323), quat=(0.707107, 0.0, 0.0, -0.707107), rgba=(0.6118, 0.4392, 0.2627, 1.0), name="siden"),
    Geom("box", (0.13, 0.007, 0.055), (2.147, -0.0, 0.323), quat=(0.707107, 0.0, 0.0, -0.707107), rgba=(0.6118, 0.4392, 0.2627, 1.0), name="sides"),
    Geom("box", (0.007, 0.086, 0.055), (2.24, 0.123, 0.323), quat=(0.707107, 0.0, 0.0, -0.707107), rgba=(0.6118, 0.4392, 0.2627, 1.0), name="sidew"),
    Geom("box", (1.1, 0.16, 0.015), (-2.35, -0.0, 0.115), quat=(0.707107, 0.0, 0.0, 0.707107), rgba=(0.6706, 0.4941, 0.3059, 1.0), name="deck"),
    Geom("box", (1.1, 0.16, 0.015), (-2.35, -0.0, 0.375), quat=(0.707107, 0.0, 0.0, 0.707107), rgba=(0.6706, 0.4941, 0.3059, 1.0), name="deck"),
    Geom("box", (1.1, 0.16, 0.015), (-2.35, -0.0, 0.245), quat=(0.707107, 0.0, 0.0, 0.707107), rgba=(0.6706, 0.4941, 0.3059, 1.0), name="deck"),
    Geom("box", (0.025, 0.16, 0.195), (-2.35, 1.1, 0.195), quat=(0.707107, 0.0, 0.0, 0.707107), rgba=(0.502, 0.3569, 0.2118, 1.0), name="upright"),
    Geom("box", (0.025, 0.16, 0.195), (-2.35, -1.1, 0.195), quat=(0.707107, 0.0, 0.0, 0.707107), rgba=(0.502, 0.3569, 0.2118, 1.0), name="upright"),
    Geom("box", (1.3, 0.16, 0.015), (0.0, 1.65, 0.115), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.6706, 0.4941, 0.3059, 1.0), name="deck"),
    Geom("box", (1.3, 0.16, 0.015), (0.0, 1.65, 0.245), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.6706, 0.4941, 0.3059, 1.0), name="deck"),
    Geom("box", (1.3, 0.16, 0.015), (0.0, 1.65, 0.375), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.6706, 0.4941, 0.3059, 1.0), name="deck"),
    Geom("box", (0.025, 0.16, 0.195), (1.3, 1.65, 0.195), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.502, 0.3569, 0.2118, 1.0), name="upright"),
    Geom("box", (0.025, 0.16, 0.195), (-1.3, 1.65, 0.195), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.502, 0.3569, 0.2118, 1.0), name="upright"),
    Geom("box", (1.1, 0.16, 0.015), (2.35, -0.0, 0.375), quat=(0.707107, 0.0, 0.0, -0.707107), rgba=(0.6706, 0.4941, 0.3059, 1.0), name="deck"),
    Geom("box", (1.1, 0.16, 0.015), (2.35, -0.0, 0.245), quat=(0.707107, 0.0, 0.0, -0.707107), rgba=(0.6706, 0.4941, 0.3059, 1.0), name="deck"),
    Geom("box", (1.1, 0.16, 0.015), (2.35, -0.0, 0.115), quat=(0.707107, 0.0, 0.0, -0.707107), rgba=(0.6706, 0.4941, 0.3059, 1.0), name="deck"),
    Geom("box", (0.025, 0.16, 0.195), (2.35, 1.1, 0.195), quat=(0.707107, 0.0, 0.0, -0.707107), rgba=(0.502, 0.3569, 0.2118, 1.0), name="upright"),
    Geom("box", (0.025, 0.16, 0.195), (2.35, -1.1, 0.195), quat=(0.707107, 0.0, 0.0, -0.707107), rgba=(0.502, 0.3569, 0.2118, 1.0), name="upright"),
    Geom("box", (0.33, 0.21, 0.015), (-1.5, -1.35, 0.198), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.502, 0.3569, 0.2118, 1.0), name="apron"),
    Geom("box", (0.018, 0.018, 0.107), (-1.815, -1.545, 0.107), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.502, 0.3569, 0.2118, 1.0), name="leg"),
    Geom("box", (0.018, 0.018, 0.107), (-1.185, -1.155, 0.107), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.502, 0.3569, 0.2118, 1.0), name="leg"),
    Geom("box", (0.018, 0.018, 0.107), (-1.185, -1.545, 0.107), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.502, 0.3569, 0.2118, 1.0), name="leg"),
    Geom("box", (0.018, 0.018, 0.107), (-1.815, -1.155, 0.107), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.502, 0.3569, 0.2118, 1.0), name="leg"),
    Geom("box", (0.35, 0.23, 0.013), (-1.5, -1.35, 0.227), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.6706, 0.4941, 0.3059, 1.0), name="top"),
    Geom("box", (0.06, 1.8, 0.65), (2.5, -0.0, 0.65), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.58, 0.58, 0.58, 1.0), name="walle_1"),
    Geom("box", (2.5, 0.06, 0.65), (0.0, 1.8, 0.65), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.58, 0.58, 0.58, 1.0), name="walln_1"),
    Geom("box", (1.05, 0.06, 0.65), (-1.45, -1.8, 0.65), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.58, 0.58, 0.58, 1.0), name="walls_1"),
    Geom("box", (1.05, 0.06, 0.65), (1.45, -1.8, 0.65), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.58, 0.58, 0.58, 1.0), name="walls_2"),
    Geom("box", (0.06, 1.8, 0.65), (-2.5, -0.0, 0.65), quat=(1.0, 0.0, 0.0, 0.0), rgba=(0.58, 0.58, 0.58, 1.0), name="wallw_1"),
    ],
)

# A tiled storeroom with painted walls and timber shelving. Keep shelf top
# surfaces exactly where the exported navigation/grasp tests put them.
# No extra grocery props: decoration must not change the stocktake's answer.
_paint = (0.78, 0.77, 0.69, 1.0)
_timber = (0.43, 0.29, 0.16, 1.0)
_grain = (0.36, 0.24, 0.13, 1.0)
_tile = (0.44, 0.48, 0.45, 1.0)
_grout = (0.32, 0.36, 0.33, 1.0)
_colors = {
    "floor": _tile, "deck": _timber, "top": _timber,
    "upright": _grain, "apron": _grain, "leg": _grain,
    "skirt": (0.29, 0.32, 0.28, 1.0),
    "ceiling": (0.87, 0.86, 0.79, 1.0),
}
ROOM.geoms = [
    replace(g, rgba=_paint if g.name.startswith("wall") else _colors.get(g.name, g.rgba))
    for g in ROOM.geoms if g.name not in ("aisle", "aisletick")
]
# 30 mm boards left only 100 mm between shelves, squeezing the 108 mm jars
# through both planks. 16 mm boards leave 114 mm; their TOPS do not move.
ROOM.geoms = [
    replace(g, size=(*g.size[:2], 0.008), pos=(*g.pos[:2], g.pos[2] + 0.007))
    if g.name == "deck" else g for g in ROOM.geoms
]
# Flush visual seams; a raised collision surface would pin the planar base.
for x in range(-6, 7):
    ROOM.geoms.append(Geom("box", (0.0015, 1.74, 0.0002), (x * 0.4, 0, 0.0002), rgba=_grout, name="grout", collide=False))
for y in range(-4, 5):
    ROOM.geoms.append(Geom("box", (2.44, 0.0015, 0.0002), (0, y * 0.4, 0.0002), rgba=_grout, name="grout", collide=False))
# Thin timber edge bands give the shelves a front face without moving the
# front lip that all of the reach calculations depend on.
for g in list(ROOM.geoms):
    if g.name != "deck":
        continue
    z = g.pos[2]
    if abs(g.pos[0]) > 2:
        x = -2.189 if g.pos[0] < 0 else 2.189
        ROOM.geoms.append(Geom("box", (0.0005, g.size[0], 0.002), (x, 0, z - 0.005), rgba=_grain, name="shelf_edge", collide=False))
    else:
        ROOM.geoms.append(Geom("box", (g.size[0], 0.0005, 0.002), (0, 1.489, z - 0.005), rgba=_grain, name="shelf_edge", collide=False))

# Shared camera-visible finishes; supports and door clearances remain above.

finish_room(ROOM)
